#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

---
apiVersion: v1
kind: Namespace
metadata:
  name: #@ data.values.developer_namespace
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: #@ data.values.developer_namespace
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K
---
apiVersion: v1 
kind: ServiceAccount
metadata:
  name: workload-user-sa
  namespace: #@ data.values.developer_namespace
secrets:
- name: registry-credentials
imagePullSecrets:
- name: registry-credentials
