---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: app-toolkit.community.tanzu.vmware.com.0.2.0
spec:
  refName: app-toolkit.community.tanzu.vmware.com
  version: 0.2.0
  releasedAt: 2022-04-11T22:03:24Z
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            #TODO: Swap this out for a projects.registry.vmware.com/tce image once
            image: index.docker.io/ryanmattcollins/apptoolkit-dev-bundle@sha256:96f8e818b2983dad49204f8a4c6bb2f3957c8fd3e0c09eccf37ffb6c4d0cc3f0
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        excluded_packages:
          type: array
          default: []
          items:
            type: string
          description:
            "A list of package refs that should be excluded from app-toolkit"
        contour:
          type: object
          default: {}
          description: "contour values"
        developer_namespace:
          type: string
          default: default
          description: "namespace to populate registry-credentials for"
        kpack:
          type: object
          default: {}
          description: "kpack values"
        kpack_dependencies:
          type: object
          default: {}
          description: "kpack_dependencies values"
        knative_serving:
          type: object
          default: {}
          description: "knative-serving values"
        cert_manager:
          type: object
          default: {}
