---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: app-toolkit.community.tanzu.vmware.com.0.2.0
spec:
  refName: app-toolkit.community.tanzu.vmware.com
  version: 0.2.0
  releasedAt: 2022-04-11T22:03:24Z
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            #TODO: Swap this out for a projects.registry.vmware.com/tce image once
            image: index.docker.io/ryanmattcollins/apptoolkit-dev-bundle@sha256:3e389a587dfa7ff7e2c425a4b4487c94b152f3e61d2693506a2ac15bfc74be72
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        excluded_packages:
          type: array
          default: []
          items:
            type: string
          description:
            "A list of package refs that should be excluded from app-toolkit"
        contour:
          type: object
          default: {}
          description: "contour values"
        cartographer_catalog:
          type: object
          default: {}
          description: "cartographer_catalog values"
        developer_namespace:
          type: string
          default: default
          description: "namespace to populate registry-credentials for"
        kpack:
          type: object
          default: {}
          description: "kpack values"
        kpack_dependencies:
          type: object
          default: {}
          description: "kpack_dependencies values"
        knative_serving:
          type: object
          default: {}
          description: "knative-serving values"
        cert_manager:
          type: object
          default: {}
